Add text and shell formatting to lint job

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -59,9 +59,6 @@ jobs:
           paths:
             - packages/*/build/*
       - run:
-          name: Format text
-          command: yarn format-text
-      - run:
           name: Check for clean workspace
           command: |
             SOURCE_CHANGES=$(git status --porcelain)
@@ -480,4 +477,22 @@ jobs:
           paths:
             - ~/.cache/yarn
       - run:
+          name: Lint
           command: yarn lint
+      - run:
+          name: Format text
+          command: yarn format-text
+      - run:
+          name: Format shell scripts
+          command: yarn format-shell
+      - run:
+          name: Check for clean workspace
+          command: |
+            SOURCE_CHANGES=$(git status --porcelain)
+            if [[ -n "$SOURCE_CHANGES" ]]; then
+              echo "Error: repository contains changes."
+              echo "Showing 'git status' and 'git diff' for debugging now:"
+              git status
+              git diff
+              exit 1
+            fi
